# 脚本元信息
[info]
# 脚本包名,建议直接用RepoName作为脚本包名，有且仅有该包名的脚本可以被引入和调用
package = "wxapputils"
# 脚本描述，介绍脚本的功能和用途
description = "微信小程序桌面端操作工具包"
# 脚本主题标签列表，如["web automation", "data extraction"]
topics = ["wxapp"]
# 脚本官方网站
website = "https://yanlingrpa.com"
# 脚本作者
author = "xuyd"
# 脚本作者邮箱
email = "sssxyd@gmail.com"
# 脚本适配的设备列表，如["windows", "mac", "ubuntu"]
devices = ["windows"]
# 脚本需要的言灵引擎版本号
engine_version = "1.0.0"

# 操作的GUI程序列表
[[gui]]
id = "meituan"
name = "美团微信小程序"
launcher = "WeChat.exe"
process = "WeChatAppEx.exe"
url = "weixin://launchapplet?appid=wx9f0c3b9e7cbb1c8&path=pages/index/index"


